name: howler
description: Audio library for the modern web. This makes working with audio in Dart easy and reliable across many platforms. (Port of howler.js to Dart)
version: 1.1.2
homepage: https://github.com/gmpassos/howler.dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  swiss_knife: ^3.1.6

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.3
